clickJSAlertBtn = "//button[text()='Click for JS Alert']"
arisLogo = "//img[@alt='ArisGlobal']"
arisHeader = "//h2[text()='Delivering safer, faster breakthroughs']"
primaryOption1 = "(//a[text()='LifeSphere'])[1]"
primaryOption2 = "(//a[text()='Who We Are'])[1]"
primaryOption3 = "(//a[text()='Our Customers'])[1]"
primaryOption4 = "(//a[text()='News'])[1]"
lifeSphereMedicalAffairs = "//span[text()='LifeSphere Medical Affairs']"
reporter = "//a[text()='Reporter']"
watchTheVideoBtn = "(//a[text()='Watch the video'])[1]"
